Account/urls.py
from django.urls import path
from . import views

app_name="account"
urlpatterns = [
    path('',views.Home,name="Home"),
    # path('register',views.Registration,name="Register"),
    path('login',views.Login,name="Login"),
    path('logout',views.loggingout,name="logout"),
]

Admin/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path("admindashboard",views.dashboard,name="admin-dashboard"),
    #Student urls
    path('add_student',views.add_student,name="add_student"),
    path('view_student',views.view_student,name='view_student'),
    path('edit_student/<int:student_id>',views.edit_student,name="edit_student"),
    path('delete_student/<int:student_id>',views.delete_student,name="delete_student"),

    #teacher urls
    path('teacher_add',views.teacher_add,name="teacher_add"),
    path('view_teacher',views.view_teacher,name="view_teacher"),
    path('edit_teacher/<str:teacher_id>',views.edit_teacher,name="edit_teacher"),
    path('delete_teacher/<str:teacher_id>',views.delete_teacher,name="delete_teacher")
]

Management/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('AdminOperation/',include('Admin.urls')),
    path('',include('Account.urls')),
    path('teacher/',include('Teacher.urls')),
    path('student/',include('Student.urls')),

]

Teacher/urls.py
from django.urls import path
from . import views
urlpatterns = [
    # path('teacherlogin',views.Teacherlogin,name="Login"),
    path('teacherdashboard',views.teacher_dashboard,name="teacher-dashboard"),
    path('profile/<str:teacher_id>',views.profile,name="profile"),
    path('add_assignment',views.add_assignment,name="add_assignment"),
    path('view_assignment',views.view_assignment,name='view_assignment'),
    path('assignment/<int:assignment_id>/submissions',views.view_submissions,name='view-submissions'),

    path('submission/<int:submission_id>/grade',views.grade_submission,name='grade-submission'),
    path('attendance/<int:subject_id>', views.take_attendance, name='take-attendance'),
    path('attendance/view/<int:subject_id>', views.view_attendance, name='view-attendance'),
]

Teacher/forms.py
from django import forms
from Admin.models import Subject,Teacher

class LoginForm(forms.Form):
    username=forms.CharField(max_length=100)
    password=forms.CharField(widget=forms.PasswordInput)

class AddAssignment(forms.Form):
    # teacher=forms.ModelChoiceField(queryset=Teacher.objects.all())
    subject = forms.ModelChoiceField(queryset=Subject.objects.all())
    title = forms.CharField(max_length=200)
    description = forms.CharField(widget=forms.Textarea)
    assigned_date = forms.DateField()
    due_date = forms.DateField()
    total_marks = forms.IntegerField()
    file = forms.FileField()

Teacher/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse
from Account.forms import LoginForm
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from Admin.models import Student,Teacher,Subject,Assignment,Attendance,Submission
from django.contrib.auth.decorators import login_required
from .forms import *
from django.utils import timezone

# Create your views here.
# def Teacherlogin(request):
#     if request.method=="POST":
#         form=LoginForm(request.POST)
#         if form.is_valid():
#             username=form.cleaned_data["username"]
#             password=form.cleaned_data["password"]
         
#             user=authenticate(request,username=username,password=password)
#             if user is not None:
#                 login(request,user)
#                 return redirect('dashboard')
#             else:
#                 messages.error(request,"You are not authorized as a teacher")
#     else:
#         form=LoginForm()        
#     return render(request,"Login.html",{'form':form})
@login_required
def add_assignment(request):
    teacher=Teacher.objects.get(user=request.user)
    if request.method == "POST":

        form = AddAssignment(request.POST, request.FILES)
        if form.is_valid():
            Assignment.objects.create(
                teacher=teacher,
                subject=form.cleaned_data['subject'],
                title=form.cleaned_data["title"],
                description=form.cleaned_data["description"],
                assigned_date=form.cleaned_data["assigned_date"],
                due_date=form.cleaned_data["due_date"],
                total_marks=form.cleaned_data["total_marks"],
                file=form.cleaned_data["file"],
            )
            return redirect('view_assignment')
    else:
        form = AddAssignment()
        form.fields['subject'].queryset=Subject.objects.filter(teacher=teacher)#shows only the teacher assigned subjects
    return render(request, "add_Assignment.html", {'form': form})


@login_required
def view_assignment(request):
    teacher = Teacher.objects.get(user=request.user)
    assignments = Assignment.objects.filter(teacher=teacher)

    return render(request, "view_assignment.html", {
        'all_assignment': assignments
    })

   
@login_required
def teacher_dashboard(request):
    teacher = get_object_or_404(Teacher, user=request.user)
    subjects = Subject.objects.filter(teacher=teacher)
    total_subjects = subjects.count()
    teacher_classes=subjects.values_list('assigned_class', flat=True)
    total_students=Student.objects.filter(Grade__in=teacher_classes).distinct().count()
    assignments = Assignment.objects.filter(teacher=teacher)
    total_assignments = assignments.count()
    today = timezone.now().date()
    today_attendance = Attendance.objects.filter(teacher=teacher,date=today).count()


    context = {
        "teacher":teacher,
        'subjects':subjects,
        'total_students': total_students,
        'total_subjects': total_subjects,
        'total_assignment':total_assignments,
        'today_attendance': today_attendance,
      
    }

    return render(request, 'teacher_dashboard.html', context)

def profile(request,teacher_id):
    teacher=get_object_or_404(Teacher,TeacherID=teacher_id)
    return render(request,"profile.html",{"teacher":teacher})

@login_required
def view_submissions(request, assignment_id):
    teacher = get_object_or_404(Teacher, user=request.user)
    assignment = get_object_or_404(Assignment, id=assignment_id, teacher=teacher)

    submissions = Submission.objects.filter(assignment=assignment)

    return render(request, "view_submissions.html", {
        "assignment": assignment,
        "submissions": submissions
    })


@login_required
def grade_submission(request, submission_id):
    teacher = get_object_or_404(Teacher, user=request.user)
    submission = get_object_or_404(Submission, id=submission_id)

    if submission.assignment.teacher != teacher:
        return HttpResponse("Unauthorized", status=403)

    if request.method == "POST":
        submission.marks_obtained = request.POST.get("marks")
        submission.feedback = request.POST.get("feedback")
        submission.save()

        return redirect("view-submissions", assignment_id=submission.assignment.id)

    return render(request, "grade_submission.html", {
        "submission": submission
    })

@login_required
def take_attendance(request, subject_id):
    teacher = get_object_or_404(Teacher, user=request.user)
    subject = get_object_or_404(Subject, id=subject_id, teacher=teacher)

    students = Student.objects.filter(Grade=subject.assigned_class)
    today = timezone.now().date()

    if request.method == "POST":
        for student in students:
            status = request.POST.get(f"status_{student.id}")

            if status:
                Attendance.objects.update_or_create(
                    student=student,
                    subject=subject,
                    date=today,
                    defaults={
                        "teacher": teacher,
                        "status": status
                    }
                )
        return redirect("view-attendance", subject_id=subject.id)

    return render(request, "take_attendance.html", {
        "subject": subject,
        "students": students,
        "today": today
    })

@login_required
def view_attendance(request, subject_id):
    teacher = get_object_or_404(Teacher, user=request.user)
    subject = get_object_or_404(Subject, id=subject_id, teacher=teacher)

    records = Attendance.objects.filter(subject=subject).order_by("-date")

    return render(request, "view_attendance.html", {
        "subject": subject,
        "records": records
    })

Teacher/templates/Profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teacher Dashboard</title>

    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f6f8;
            margin: 0;
            padding: 0;
        }

        .navbar {
            background-color: #2c7be5;
            padding: 15px 30px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .navbar h1 {
            color: white;
            margin: 0;
            font-size: 22px;
        }

        .nav-links a {
            color: white;
            text-decoration: none;
            margin-left: 20px;
            font-weight: 500;
        }

        .nav-links a:hover {
            text-decoration: underline;
        }

        .container {
            width: 90%;
            margin: 30px auto;
        }

        .cards {
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
            justify-content: space-between;
        }

        .card {
            background: white;
            padding: 20px;
            border-radius: 12px;
            flex: 1 1 22%;
            box-shadow: 0 8px 20px rgba(0,0,0,0.1);
            text-align: center;
            transition: transform 0.2s;
        }

        .card:hover {
            transform: translateY(-5px);
        }

        .card h2 {
            margin: 0;
            font-size: 36px;
            color: #2c7be5;
        }

        .card p {
            margin: 10px 0 0;
            font-size: 16px;
            color: #555;
        }

        .dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: white;
            min-width: 180px;
            box-shadow: 0px 8px 16px rgba(0,0,0,0.2);
            border-radius: 6px;
            z-index: 1;
        }

        .dropdown-content a {
            color: #2c7be5;
            padding: 8px 12px;
            text-decoration: none;
            display: block;
        }

        .dropdown-content a:hover {
            background-color: #f1f1f1;
        }

        .dropdown:hover .dropdown-content {
            display: block;
        }

    </style>
</head>

<body>

<div class="navbar">
    <h1>Teacher Dashboard - {{ user.username }}</h1>

    <div class="nav-links">
        <a href="{% url 'teacher-dashboard' %}">Dashboard</a>
        <a href="{% url 'add_assignment' %}">Add Assignment</a>
        <a href="{% url 'view_assignment' %}">View Assignment</a>
        {% comment %} <a href="{% url 'take-attendance'   %}">Attendance</a> {% endcomment %}

         <div class="dropdown">
            <a href="#">Attendance ▼</a>
            <div class="dropdown-content">
                {% for subject in subjects %}
                    <a href="{% url 'take-attendance' subject.id %}">
                        Take - {{ subject.subject_name }}
                    </a>
                    <a href="{% url 'view-attendance' subject.id %}">
                        View - {{ subject.subject_name }}
                    </a>
                {% empty %}
                    <a>No Subjects</a>
                {% endfor %}
            </div>
        </div>

        
        <a href="{% url 'account:logout' %}" 
        style="background:#dc3545; padding:6px 12px; border-radius:6px;">
            Logout
        </a>       
    </div>
</div>

<div class="container">
    <h2>Profile</h2>
    <p>ID:{{teacher.TeacherID}}</p>
    <p>Name:{{teacher.Teachername}}</p>
    <p>Department:{{teacher.department}}</p>
    <p>Username:{{teacher.username}}</p>
    <p>Password:{{teacher.password}}</p>
    

Teacher/templates/add_Assignment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teacher Dashboard</title>

    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f6f8;
            margin: 0;
            padding: 0;
        }

        .navbar {
            background-color: #2c7be5;
            padding: 15px 30px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .navbar h1 {
            color: white;
            margin: 0;
            font-size: 22px;
        }

        .nav-links a {
            color: white;
            text-decoration: none;
            margin-left: 20px;
            font-weight: 500;
        }

        .nav-links a:hover {
            text-decoration: underline;
        }

        .container {
            width: 90%;
            margin: 30px auto;
        }

        .cards {
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
            justify-content: space-between;
        }

        .card {
            background: white;
            padding: 20px;
            border-radius: 12px;
            flex: 1 1 22%;
            box-shadow: 0 8px 20px rgba(0,0,0,0.1);
            text-align: center;
            transition: transform 0.2s;
        }

        .card:hover {
            transform: translateY(-5px);
        }

        .card h2 {
            margin: 0;
            font-size: 36px;
            color: #2c7be5;
        }

        .card p {
            margin: 10px 0 0;
            font-size: 16px;
            color: #555;
        }

        .dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: white;
            min-width: 180px;
            box-shadow: 0px 8px 16px rgba(0,0,0,0.2);
            border-radius: 6px;
            z-index: 1;
        }

        .dropdown-content a {
            color: #2c7be5;
            padding: 8px 12px;
            text-decoration: none;
            display: block;
        }

        .dropdown-content a:hover {
            background-color: #f1f1f1;
        }

        .dropdown:hover .dropdown-content {
            display: block;
        }
        @media (max-width: 768px) {
            .dashboard {
                flex-direction: column;
                align-items: center;
            }
        }
        button{
            background-color:Green;
            color:white;
        }
    </style>
</head>

<body>

<div class="navbar">
    <h1>Teacher Dashboard - {{ user.username }}</h1>

    <div class="nav-links">
        <a href="{% url 'teacher-dashboard' %}">Dashboard</a>
        <a href="{% url 'add_assignment' %}">Add Assignment</a>
        <a href="{% url 'view_assignment' %}">View Assignment</a>
        {% comment %} <a href="{% url 'take-attendance'   %}">Attendance</a> {% endcomment %}

         <div class="dropdown">
            <a href="#">Attendance ▼</a>
            <div class="dropdown-content">
                {% for subject in subjects %}
                    <a href="{% url 'take-attendance' subject.id %}">
                        Take - {{ subject.subject_name }}
                    </a>
                    <a href="{% url 'view-attendance' subject.id %}">
                        View - {{ subject.subject_name }}
                    </a>
                {% empty %}
                    <a>No Subjects</a>
                {% endfor %}
            </div>
        </div>
        <a href="{% url 'account:logout' %}" 
        style="background:#dc3545; padding:6px 12px; border-radius:6px;">
            Logout
        </a>       
    </div>
</div>


<div class="container">
    <h2>Add Assignment</h2>

    <form method="post" action={% url 'add_assignment'%} enctype="multipart/form-data">

        {% csrf_token %}
        
        {{ form.as_p }}
        
        <button type="submit">Add Assignment</button>
    </form>
</div>

Teacher/templates/grade_submission.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teacher Dashboard</title>

    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f6f8;
            margin: 0;
            padding: 0;
        }

        .navbar {
            background-color: #2c7be5;
            padding: 15px 30px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .navbar h1 {
            color: white;
            margin: 0;
            font-size: 22px;
        }

        .nav-links a {
            color: white;
            text-decoration: none;
            margin-left: 20px;
            font-weight: 500;
        }

        .nav-links a:hover {
            text-decoration: underline;
        }

        .container {
            width: 90%;
            margin: 30px auto;
        }

        .cards {
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
            justify-content: space-between;
        }

        .card {
            background: white;
            padding: 20px;
            border-radius: 12px;
            flex: 1 1 22%;
            box-shadow: 0 8px 20px rgba(0,0,0,0.1);
            text-align: center;
            transition: transform 0.2s;
        }

        .card:hover {
            transform: translateY(-5px);
        }

        .card h2 {
            margin: 0;
            font-size: 36px;
            color: #2c7be5;
        }

        .card p {
            margin: 10px 0 0;
            font-size: 16px;
            color: #555;
        }

        .dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: white;
            min-width: 180px;
            box-shadow: 0px 8px 16px rgba(0,0,0,0.2);
            border-radius: 6px;
            z-index: 1;
        }

        .dropdown-content a {
            color: #2c7be5;
            padding: 8px 12px;
            text-decoration: none;
            display: block;
        }

        .dropdown-content a:hover {
            background-color: #f1f1f1;
        }

        .dropdown:hover .dropdown-content {
            display: block;
        }
        @media (max-width: 768px) {
            .dashboard {
                flex-direction: column;
                align-items: center;
            }
        }

    </style>
</head>

<body>

<div class="navbar">
    <h1>Teacher Dashboard - {{ user.username }}</h1>

    <div class="nav-links">
        <a href="{% url 'teacher-dashboard' %}">Dashboard</a>
        <a href="{% url 'add_assignment' %}">Add Assignment</a>
        <a href="{% url 'view_assignment' %}">View Assignment</a>
        {% comment %} <a href="{% url 'take-attendance'   %}">Attendance</a> {% endcomment %}

         <div class="dropdown">
            <a href="#">Attendance ▼</a>
            <div class="dropdown-content">
                {% for subject in subjects %}
                    <a href="{% url 'take-attendance' subject.id %}">
                        Take - {{ subject.subject_name }}
                    </a>
                    <a href="{% url 'view-attendance' subject.id %}">
                        View - {{ subject.subject_name }}
                    </a>
                {% empty %}
                    <a>No Subjects</a>
                {% endfor %}
            </div>
        </div>
        <a href="{% url 'account:logout' %}" 
        style="background:#dc3545; padding:6px 12px; border-radius:6px;">
            Logout
        </a>       
    </div>
</div>
    <h2>Grade Submission</h2>

    <p><strong>Student:</strong> {{ submission.student }}</p>
    <p><strong>Assignment:</strong> {{ submission.assignment.title }}</p>

    <p>
        <strong>Submitted File:</strong>
        <a href="{{ submission.submitted_file.url }}" target="_blank">
            Download File
        </a>
    </p>

    <hr>

    <form method="POST">
        {% csrf_token %}

        <label>Marks:</label><br>
        <input type="number"
               name="marks"
               value="{{ submission.marks_obtained }}"
               required>
        <br><br>

        <label>Feedback:</label><br>
        <textarea name="feedback" rows="4" cols="50">
{{ submission.feedback }}
        </textarea>
        <br><br>

        <button type="submit">Save Grade</button>
    </form>

    <br>
    <a href="{% url 'view-submissions' submission.assignment.id %}">
        Back to Submissions
    </a>

</body>
</html>

Teacher/templates/take_attendance.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teacher Dashboard</title>

    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f6f8;
            margin: 0;
            padding: 0;
        }

        .navbar {
            background-color: #2c7be5;
            padding: 15px 30px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .navbar h1 {
            color: white;
            margin: 0;
            font-size: 22px;
        }

        .nav-links a {
            color: white;
            text-decoration: none;
            margin-left: 20px;
            font-weight: 500;
        }

        .nav-links a:hover {
            text-decoration: underline;
        }

        .container {
            width: 90%;
            margin: 30px auto;
        }

        .cards {
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
            justify-content: space-between;
        }

        .card {
            background: white;
            padding: 20px;
            border-radius: 12px;
            flex: 1 1 22%;
            box-shadow: 0 8px 20px rgba(0,0,0,0.1);
            text-align: center;
            transition: transform 0.2s;
        }

        .card:hover {
            transform: translateY(-5px);
        }

        .card h2 {
            margin: 0;
            font-size: 36px;
            color: #2c7be5;
        }

        .card p {
            margin: 10px 0 0;
            font-size: 16px;
            color: #555;
        }

        .dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: white;
            min-width: 180px;
            box-shadow: 0px 8px 16px rgba(0,0,0,0.2);
            border-radius: 6px;
            z-index: 1;
        }

        .dropdown-content a {
            color: #2c7be5;
            padding: 8px 12px;
            text-decoration: none;
            display: block;
        }

        .dropdown-content a:hover {
            background-color: #f1f1f1;
        }

        .dropdown:hover .dropdown-content {
            display: block;
        }
        @media (max-width: 768px) {
            .dashboard {
                flex-direction: column;
                align-items: center;
            }
        }
    </style>
</head>

<body>

<div class="navbar">
    <h1>Teacher Dashboard - {{ user.username }}</h1>

    <div class="nav-links">
        <a href="{% url 'teacher-dashboard' %}">Dashboard</a>
        <a href="{% url 'add_assignment' %}">Add Assignment</a>
        <a href="{% url 'view_assignment' %}">View Assignment</a>
        {% comment %} <a href="{% url 'take-attendance'   %}">Attendance</a> {% endcomment %}

         <div class="dropdown">
            <a href="#">Attendance ▼</a>
            <div class="dropdown-content">
                {% for subject in subjects %}
                    <a href="{% url 'take-attendance' subject.id %}">
                        Take - {{ subject.subject_name }}
                    </a>
                    <a href="{% url 'view-attendance' subject.id %}">
                        View - {{ subject.subject_name }}
                    </a>
                {% empty %}
                    <a>No Subjects</a>
                {% endfor %}
            </div>
        </div>
        <a href="{% url 'account:logout' %}" 
        style="background:#dc3545; padding:6px 12px; border-radius:6px;">
            Logout
        </a>       
    </div>
</div>
<h2>Take Attendance - {{ subject.subject_name }}</h2>
<p>Date: {{ today }}</p>

<form method="POST">
    {% csrf_token %}
    <table border="1" cellpadding="8">
        <tr>
            <th>Student</th>
            <th>Status</th>
        </tr>

        {% for student in students %}
        <tr>
            <td>{{ student.Firstname }} {{ student.Lastname }}</td>
            <td>
                <select name="status_{{ student.id }}">
                    <option value="Present">Present</option>
                    <option value="Absent">Absent</option>
                    <option value="Leave">Leave</option>
                </select>
            </td>
        </tr>
        {% endfor %}
    </table>

    <br>
    <button type="submit">Save Attendance</button>
</form>

Teacher/templates/teacher_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teacher Dashboard</title>

    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f6f8;
            margin: 0;
            padding: 0;
        }

        .navbar {
            background-color: #2c7be5;
            padding: 15px 30px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .navbar h1 {
            color: white;
            margin: 0;
            font-size: 22px;
        }

        .nav-links a {
            color: white;
            text-decoration: none;
            margin-left: 20px;
            font-weight: 500;
        }

        .nav-links a:hover {
            text-decoration: underline;
        }

        .container {
            width: 90%;
            margin: 30px auto;
        }

        .cards {
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
            justify-content: space-between;
            margin-top:100px;
        }

        .card {
            background: white;
            padding: 20px;
            border-radius: 12px;
            flex: 1 1 22%;
            box-shadow: 0 8px 20px rgba(0,0,0,0.1);
            text-align: center;
            transition: transform 0.2s;
        }

        .card:hover {
            transform: translateY(-5px);
        }

        .card h2 {
            margin: 0;
            font-size: 36px;
            color: #2c7be5;
        }

        .card p {
            margin: 10px 0 0;
            font-size: 16px;
            color: #555;
        }

        .dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: white;
            min-width: 180px;
            box-shadow: 0px 8px 16px rgba(0,0,0,0.2);
            border-radius: 6px;
            z-index: 1;
        }

        .dropdown-content a {
            color: #2c7be5;
            padding: 8px 12px;
            text-decoration: none;
            display: block;
        }

        .dropdown-content a:hover {
            background-color: #f1f1f1;
        }

        .dropdown:hover .dropdown-content {
            display: block;
        }
        @media (max-width: 768px) {
            .dashboard {
                flex-direction: column;
                align-items: center;
            }
        }
    </style>
</head>

<body>

<div class="navbar">
    <h1>Teacher Dashboard - {{ user.username }}</h1>

    <div class="nav-links">
        <a href="{% url 'teacher-dashboard' %}">Dashboard</a>
        <a href="{% url 'add_assignment' %}">Add Assignment</a>
        <a href="{% url 'view_assignment' %}">View Assignment</a>
        {% comment %} <a href="{% url 'take-attendance'   %}">Attendance</a> {% endcomment %}

         <div class="dropdown">
            <a href="#">Attendance ▼</a>
            <div class="dropdown-content">
                {% for subject in subjects %}
                    <a href="{% url 'take-attendance' subject.id %}">
                        Take - {{ subject.subject_name }}
                    </a>
                    <a href="{% url 'view-attendance' subject.id %}">
                        View - {{ subject.subject_name }}
                    </a>
                {% empty %}
                    <a>No Subjects</a>
                {% endfor %}
            </div>
        </div>
        
        <a href="{% url 'account:logout' %}" 
        style="background:#dc3545; padding:6px 12px; border-radius:6px;">
            Logout
        </a>       
    </div>
</div>

<div class="container">
    <div class="cards">
        <div class="card">
            <h2>{{ total_students }}</h2>
            <p>Total Students</p>
        </div>

        <div class="card">
            <h2>{{ total_subjects }}</h2>
            <p>My Subjects</p>
        </div>

        <div class="card">
            <h2>{{ total_assignment }}</h2>
            <p>Assignments</p>
        </div>
{% comment %} 
        <div class="card">
            <h2>{{ today_attendance }}</h2>
            <p>Attendance Today</p>
        </div> {% endcomment %}
    </div>
</div>

</body>
</html>